# default config
baseURL = "https://waldocorp.com"
languageCode = "en-us"
title = "waldoCorp"
theme = "hugo-creative-portfolio-theme"
summaryLength = "10"
paginate = 6


#[[menu.main]]
#name = "Contact"
#URL = "contact"
#weight = 3


# deult parameter
[params]
  style = "pink"
  logo = "images/logo.png"
  home = "Home"

  # Meta data
  description = "Homepage for waldoCorp"

  sidebarAbout = [
    "Composed of Lief and Ben, waldoCorp is an assembly of projects we have worked on"
  ]

  copyright = "Copyright &copy; 2020 waldoCorp"

  email = "contact@waldocorp.com"

  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Contact"
  url = "mailto:contact@waldocorp.com"

  [params.social]

#  facebook      = "full page or profile url in facebook"
#  googleplus    = "full profile url in googleplus"
#  email         = "contact@waldocorp.com"
#  twitter       = "full profile url in twitter"
#  linkedin      = "full profile url in linkedin"
#  stackoverflow = "full profile url in stackoverflow"
#  instagram     = "full profile url in instagram"
  github        = "https://github.com/waldoCorp"

# Allow raw html for links?
[markup]
  defaultMarkdownHandler = "blackfriday"
